### ISSUE TITLE
Question about handling progress bars / carriage returns with Logalize

### ISSUE THREAD

**Issue by Beleth-D** [deponian/logalize#7]
Hello,

first of all, thanks for creating and maintaining Logalize — it looks like a very promising and modern tool for log coloring and highlighting!

I’m trying to use Logalize to colorize the output of a Python application (python main.py), which produces progress bars that update on the same line using carriage returns (\r). However, when I pipe the output through Logalize, the progress bar stops updating properly and seems to be "skipped" or broken.

I have tried using the -s (disable ANSI stripping) and -N (disable built-ins) options, but the issue persists. It looks like Logalize’s line-based matching or processing interferes with the dynamic progress bar output that relies on rewriting the same line.

My question is:
Is there a recommended way to configure Logalize, or an upcoming feature, that supports handling progress bars or other terminal output that uses carriage returns (\r) without losing the dynamic visual updates?
Or, alternatively, is there any advice on how to preserve progress bars when using Logalize for log colorization?

Thank you very much for your time and help!

Best regards,

**Comment by Beleth-D** [comment]
@deponian Tested and now it works! Thank you so much bro ❤️
I have a quick question: I'm trying to highlight the progress bar using a custom pattern and theme. Here's the relevant part of my setup:

```
patterns:
  loading-bar:
    regexp: '(^\d{1,3}%\|[^\|]+\|\s*\d+/\d+\s+\[.*\])'

themes:
  mytheme:
    patterns:
      loading-bar:
        fg: "#B74C60"

settings:
  style: dark
  theme: mytheme

```
It works, but the color only appears when the progress reaches 100% — not during the intermediate steps. Is this the expected behavior? Or is there a way to make it apply the color live throughout the progress?

Thanks again for the great project!
